# Generated by Django 5.1.1 on 2024-10-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='booked_by',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='booking_duration',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='idk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
