# Generated by Django 5.1.1 on 2024-10-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_rename_title_event_name_remove_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='booked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='booked_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='booking_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
